### ISSUE TITLE
Add an "about" section for people who don't know what arena is

### ISSUE THREAD

**Issue by gumOnShoe** [Trackrise/ANrena#6]
There should probably be a description before the draft begins about how arena works, what the intention is, that it's like drafting, etc so that people who get linked to it randomly from jnet and have never played hearthstone understand what's going on.

Make it out of the way in a box below deck selection, maybe hide it while the draft is going on. And have a simple explanation of what to do and how to play a game once the draft resolves.

**Comment by porfyalum** [comment]
I implemented an area for this bt i am quite bad on writing text, and not sure what to write in there if anyone can help with that.

**Comment by Trackrise** [comment]
Implemented on the Experimental branch. Let me know if anything is wrong.

**Comment by Trackrise** [comment]
I'm feeling good about the latest changes to the experimental branch. Let me know if anything's wrong. 

    On Saturday, October 22, 2016 6:17 AM, porfyalum <notifications@github.com> wrote:
 

 I implemented an area for this bt i am quite bad on writing text, and not sure what to write in there if anyone can help with that.—

**Comment by Trackrise** [comment]
This is on the verge of being a thing, the content just isn't there yet. The buttons you see at the top "Home, About" have been there for about a week, but they just need the actual HTML to be added. Very soon. 

    On Thursday, October 20, 2016 12:40 PM, gumOnShoe <notifications@github.com> wrote:
 

 There should probably be a description about how arena works, what the intention is, that it's like drafting, etc so that people who get linked to it randomly from jnet and have never played hearthstone understand what's going on.—
